name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci --config auto
      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@v3.63.5
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --debug --only-verified
      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Build the library
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.10-dev
          make build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload library to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./memodoor_inject.so
          asset_name: memodoor_inject.so
          asset_content_type: application/octet-stream
